#!/usr/bin/with-contenv bash

# Change permission for all execute files
chmod -R +x /etc/cont-init.d
chmod -R +x /etc/services.d

echo "Application folder belongs to nginx:nginx"

# Both developer and application must be able modify it
#chown -Rc nginx:nginx .
ls | grep -v node_modules | grep -v vendor | xargs -n1 chown -R nginx:nginx
find . -type d -exec chmod 775 {} \;
find . -type f -exec chmod ug+rw {} \;

echo "Nginx should be able to write uploaded files to temporary directory"
chown root:nginx /tmp
chmod 775 /tmp
chmod 775 /var/log

# New group