#!/usr/bin/with-contenv bash

# Change permission for all execute files
chmod -R +x /etc/cont-init.d
chmod -R +x /etc/services.d

echo "Application folder belongs to nginx:nginx"

# Both developer and application must be able modify it
# Note: Don't need on Linux/Mac but need for Windows.
#chown -Rc nginx:nginx .
chown nginx:nginx .

echo "Nginx should be able to write uploaded files to temporary directory"
chown root:nginx /tmp
chmod 775 /tmp
# For setting <DOCKER_DIR>/etc/php7/php-fpm.d/webapp.conf
chmod 775 /var/log

# New group