#!/usr/bin/with-contenv bash

echo "================ Update system permissions ================"

echo "Change permission for all execute files"
chmod -R +x /etc/cont-init.d
chmod -R +x /etc/services.d

echo "Nginx should be able to write uploaded files to temporary directory"
chown root:nginx /tmp
chmod 775 /tmp
chmod 775 /var/log

# New group
